version: '3.7'

services:
  php:
    container_name: example-php
    build: ./.docker/infra/${APP_ENV}/php
    volumes:
      - ./backend/laravel/:/var/www:cached
    environment:
      PHP_IDE_CONFIG: serverName=docker-debug

  nginx:
    image: nginx
    container_name: example-nginx
    ports:
      - '8200:80'
      - '8289:443'
    volumes:
      - ./backend/laravel/:/var/www:cached
      - ./.docker/infra/${APP_ENV}/nginx/example.conf:/etc/nginx/conf.d/example.conf
      - ./.docker/infra/${APP_ENV}/nginx/certs/:/etc/nginx/certs/
